---
language: 'node_js'
node_js:
  - "5.9.0"

sudo: false

env:
  global:
    - 'AWS_DEFAULT_REGION=us-east-1'
    - 'AWS_ACCESS_KEY_ID=AKIAJAILV2OUYHPANMRA'
    - secure: "VlWMMWtHeA+fuNXvbBG/hMvaTd/6vB+twW0zjf3s2vF7qtkVCB+TZ/xbO0iDpk6O/eoFaiIddR+5tPCf1glBqdEFAxTibM+MNHB6AlFOgjmRosqdRDjtAe4zAUJdW8JIvEn67N9Rlw3lqthMcr7bvDENUnRjJAqVJf7TroKLy+B7SZig8gln4pk9gaGFof72SYr3FKkve5DxLDjJZP1i2XUON4D3vCG/Wp1j0lZfUAfNLIAqx7peUUnJO0okLfX4wymAVgBtRw/UgpSDzpqpS4BpWx4gk7IVbqDLmb/ma/hMPGMDjPi9fOFnqhUf5puKa2rtaC2r8QN0/UEpSonlOFEhbsg9lNWBFY3tT6XUNICdn8D6RqzkOczywI9BOSYlJew9VB1a92wD5WBHec+pYDpOgPSVnz2UEtyujsmDWzfUwBuUfdDW90VHQ7h961sTxhvcfPyAYhM6DWqeChV7IrYwepkCxu2cTg/UVAHmYpFp6ztgwwVFZxzfQXlVw7Q9AnWaz/K8igEs43+tqiQXHHtPPrABhVKZbzU4plqAyIBQZ3iAMLZ97skfma32FGrfmUlsR9pGORU/gedmBijh6XJDr0Y5L1hY82NT0Xlea/S9JFh3m2TJQ3gixv6eoL+6Vd/C7eu14qiGus67HE4lkpBVjWWhgDNC6Qy3q8Y7uso="

addons:
  apt:
    packages:
      - 'lcov'

cache:
  directories:
    - 'node_modules'
    - 'bower_components'
    - 'travis-phantomjs'

before_install:
  - "mkdir -p travis-phantomjs"
  - '[ -f travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin/phantomjs ] || (wget --quiet -O $PWD/travis-phantomjs/phantomjs.tar.bz2 https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && tar -xf $PWD/travis-phantomjs/phantomjs.tar.bz2 -C $PWD/travis-phantomjs && rm $PWD/travis-phantomjs/phantomjs.tar.bz2)'
  - 'export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH'
  - "npm config set spin false"
  - "npm install -g npm@^2"
  - "npm install -g ember-cli@2.4.2"
  - "npm install -g bower@1.7.1"

install:
  - "make install"

script:
  - "make test"

after_success:
  - 'cat lcov.dat | `npm bin`/coveralls'

before_deploy:
  - 'gem install s3_website'

deploy:
  - provider: 'script'
    script: 'make build-staging && S3_WEBSITE_BUCKET="my-staging.tidycat.io" CLOUDFRONT_DISTRIBUTION_ID="E2GRWC8SMPCPLU" s3_website push'
    skip_cleanup: true
    on:
      repo: 'tidycat/user-interface'
      branch: 'master'
  - provider: 'script'
    script: 'make build-production && S3_WEBSITE_BUCKET="my.tidycat.io" CLOUDFRONT_DISTRIBUTION_ID="E3FV7OXV0MZO68" s3_website push'
    skip_cleanup: true
    on:
      repo: 'tidycat/user-interface'
      tags: true

notifications:
  email: false
  irc:
    channels:
      - secure: "Z5V+fgvPZ2QcPBUSuSH7+a2g07DhK6LDepF0FPgwUWPqYouKbSNm9t0s/+UvTmKujPrZ0cLOL+1P74m3JSJFq1FIb7QiYpLI4hpvdR9nvLrGGthJ5FrohsdqKBjXrisRaCGq6an9V31fbKfF1JKqB6pTEslGxv/XkkRl+eEvbbHnCzmI9tksesOnIL63OAyBUMEQYLXaC6IAy6jkFxzZ42oyJB8PQO12019uQu4yz0LMe//OBK5RQJFZYboL4HC96i77s1zLFaS5nZ+ay4Qr8vy8w0Lwqi0JB/TzUQV5yvd+DpYrt9A29XqoGR+R6Mogzpg+jfS6WV1rgYmOtdKFonT66TmAU6CctZzJkXtLQljkiBmr74mXJKJMR3WVRcafGjclYj2RNej0AG3S29g8z0znrmO8dysDd7415tn8YVbDNka4YkcfmtdDAX0HSTgNEGGPd9M42ffY1Hv7lvwpKicMTyc7VqIWyXUOmFvTYEPEXtgyeYjSqolKNQ/yLkCFskUk3iOzNdE80PSQT6ejXlbv+CRoKBbdM94y20OcKz17H3tKsAC3oqwaPPrp4fTF/qOrtFKv6Y5zEyfCVTaja0+qVB0oOo79ulNQn+jSqDDfuu517xp9aW25F5hBjFTbLPfUxQ3RaQ+Po1lS4tbNI6L/ImaP7/mtvgLjH78VTng="
    on_success: "change"
    on_failure: "change"
